### ISSUE TITLE
punish-combat-log removes lives without reason whenever logging out even outside combat.

### ISSUE THREAD

**Issue by WinterVein** [TinyTank800/TinyLives#12]
### Have you checked the [wiki](https://www.okamisquadron.com/wikis/tinylives) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/TinyTank800/TinyLives/projects/1) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/JFQK2aQNXr)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/TinyTank800/TinyLives/issues?q=is%3Aissue) for a similar problem?
Yes/No

### To Reproduce
1. set punish-combat-log to true
2. join game
3. logout (outside of combat)
4. log back in and see you have one less lives

### Expected behavior
No life should be subtracted during logouts
### Versions:
 - Minecraft 1.18 Spigot
 - Tinylives  3.2.2 & 3.2.1

**Comment by TinyTank800** [comment]
I will look into this after work. This easily could be true since things like this were happening in my server but we were not sure if it was combat or just leaving.

**Comment by TinyTank800** [comment]
So far just from looking at all my code the only time it removes lives is on leave for combat log and its setup correctly. I will investigate in my test server now but if you change debug to 2 and restart. When you leave does it say "Player has been punished for combat logging."

**Comment by TinyTank800** [comment]
From testing I cannot find a way to reproduce this? One of your players may have a bugged combat state in their config for the players.yml. You can check if its stuck on InCombat: true and if so either change it or have them enter combat and wait the selected time for it to go away and it should be set to false.

**Comment by WinterVein** [comment]
I will test it later with debug on and get back to you.
