### ISSUE TITLE
Command to allow admin to choose assassin

### ISSUE THREAD

**Issue by killerklown420** [TinyTank800/TinyLives#14]
### Have you checked the [wiki](https://www.okamisquadron.com/wikis/tinylives) page to see if your suggestion is already added?
Yes/No
yes
### Have you checked the [issue tracker](https://github.com/TinyTank800/TinyLives/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?
Yes/No
yes
### Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/JFQK2aQNXr)? *(Or got redirected to a Github issue here)*
Yes/No
yes
### Additional context

any chance of a future update with a command to trigger the assassin to be chosen? i think it would be a great idea to have a command for server admins to have a command to randomly choose a new assassin.

**Comment by TinyTank800** [comment]
This is able to be done with the new manual assassin system added recently. Make sure manual assassin is enabled and do /tinylives assassin playername
If random is enabled the server will choose a random assassin who is online.
