### ISSUE TITLE
Combat logging to lose your final life does not set you to spectator mode

### ISSUE THREAD

**Issue by whimsicalities** [TinyTank800/TinyLives#15]
### Have you checked the [wiki](https://www.okamisquadron.com/wikis/tinylives) page to see if there is a solution for your bug?
That page doesn't exist, so no...?

### Have you looked at the [Current bugs project](https://github.com/TinyTank800/TinyLives/projects/1) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/JFQK2aQNXr)? *(Or got redirected to a Github issue here)*
No- this is clearly a  bug, though, not an issue I'm having.

### Did you search the [issue tracker](https://github.com/TinyTank800/TinyLives/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
When you lose your last life to combat logging, you are still in survival mode and therefore effectively not dead.

### To Reproduce
1. Set combat logging punishment to true.
2. Get down to one life
3. Start combat and leave server immediately
4. Upon logging back in, you are 'dead' but still in survival mode

### Expected behavior
The player should be set to spectator mode, as they are dead. (Or banned, or whatever the config is set to.)

### Screenshots/videos
-

### Versions:
 - Minecraft: 1.19.4 Paper
 - Tinylives: 3.2.4

### Additional context/Config files
-

**Comment by TinyTank800** [comment]
This was fixed in the 3.2.5 update I just released. Thank you for reporting the bug!
