### ISSUE TITLE
Issue with variables when printing to chat

### ISSUE THREAD

**Issue by saverofthewos** [TinyTank800/TinyLives#18]
### Have you checked the [wiki](https://www.okamisquadron.com/wikis/tinylives) page to see if there is a solution for your bug?
No, the page is missing.

### Have you looked at the [Current bugs project](https://github.com/TinyTank800/TinyLives/projects/1) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/JFQK2aQNXr)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/TinyTank800/TinyLives/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
Variables do not seem to convert to what they are supposed to display when printed to chat or a title, atleast on aternos (may happen on other services, untested) .

### To Reproduce
1. Create a server with aternos with tinylives installed. (untested on other hosting services)
2. Some sort of message should appear
3. Should say something along the lines of "You have %tinylives_lives% lives!"
4. Will also happen when a player dies.
### Expected behavior
Should instead say something along the lines of "You have 3 lives!"
### Screenshots/videos
![image](https://github.com/TinyTank800/TinyLives/assets/153536079/5dc4c20f-5723-4c91-9fb5-75dfa24a3c93)

### Versions:
 - Minecraft: 1.20.4 Paper (issue also present on spigot)
 - Tinylives: 3.3.5

### Additional context/Config files
https://pastebin.com/XwUxJ8nE

I'm not sure if this is aternos specific since I don't have access to anything else.

**Comment by TinyTank800** [comment]
Make sure you have placeholder api installed for placeholders to work

**Comment by saverofthewos** [comment]
ohh
