### ISSUE TITLE
Fix ResetAll command

### ISSUE THREAD

**Issue by Tylwen** [TinyTank800/TinyLives#2]
The resetall command does not seem to work.
Shouldn't this command reset the lives of all players?

**Comment by TinyTank800** [comment]
Ah yes i think this one got lost during updates when i reformatted some stuff. I will get this fixed.

**Comment by Tylwen** [comment]
https://github.com/TinyTank800/TinyLives/blob/4f3ab622ef60dd6708134c83c3aeebe05cff9859/src/main/java/me/tinytank800/tinylives/tinylives.java#L973

**Comment by TinyTank800** [comment]
From what I see I did for this part is it sets the delay to a low number so next check it triggers but this is only used for global life resets. Would you like me to make this reset everyone to a set amount of lives? Don't think this command is used in its current state right now.

**Comment by Tylwen** [comment]
For me, a resetall should reset all player lives to their maximum life numbers.

**Comment by TinyTank800** [comment]
This will be fixed in the upcoming update 3.2.0 along with the start to MySQL which will not be functional in 3.2.0. I have a lot of coding to do to get the mysql working fully replacing the players.yml
