### ISSUE TITLE
Modify max lives command

### ISSUE THREAD

**Issue by Tylwen** [TinyTank800/TinyLives#4]
Have a command to modify the number of max life and max extra life.
and / Or to create a group system in the config file where you need a defined permission to have these advantages

**Comment by TinyTank800** [comment]
You can do this using normal perms but i have never tested a max of 0. Give the player  tinylives.maxextralives.# or tinylives.maxlives.#

I think you can also change it in the players.yml and if so i will add a command for it or make it so that sort of thing works.

**Comment by Tylwen** [comment]
Permissions don't work

**Comment by TinyTank800** [comment]
permission should work on relog or maybe reload. I am currently working on a command for changing these as well.

**Comment by TinyTank800** [comment]
/tinylives setmaxlives player amount and /tinylives setmaxextralives player amount are both being added in the upcoming update. These will be overridden if the players tinylives.maxlives.# perms are a higher number than the config value.
