### ISSUE TITLE
DeadMan world teleport on reset/add life /respawn /reset commands still not working with version 3.2.0

### ISSUE THREAD

**Issue by BigMackTV** [TinyTank800/TinyLives#9]
### Have you checked the [wiki](https://www.okamisquadron.com/wikis/tinylives) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/TinyTank800/TinyLives/projects/1) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/JFQK2aQNXr)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/TinyTank800/TinyLives/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
DeadMans world still seems to not be teleporting myself back once I've died and either done /tl respawn (username) or used the /add life command via a purchase gui. Using the plugin version 3.2.1 and using 1.18.1 Minecraft version.

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
![Tiny Lives DeadMans world command reset issue](https://user-images.githubusercontent.com/96125463/147605078-73cf0df7-8152-40c6-9dbf-eb8293f3dd4e.JPG)

**Comment by TinyTank800** [comment]
Should be fixed in v3.2.2 from my testing. Doing it ingame and console both worked. This also has fixed a few other parts where this would not work and now checks it incase they are inside the dead world.
